################## Project Specific Entries #######################
#
# These values override other definitions
#
# Project name

PROJECT=roach2_cpld
REV_MAJOR=1
REV_MINOR=0
REV_RCS:=0

# Pin Constraints
PCFILE=constraints/roach2_cpld.ucf
# Enter your source files here space seperated
#      Note: no spaces in filenames
SRC=./modules/toplevel/hdl/toplevel.v \
    ./modules/mmc_infrastructure/hdl/mmc_infrastructure.v \
    ./modules/mmc_controller/hdl/mmc_controller.v \
    ./modules/mmc_controller/hdl/wr_adv.v \
    ./modules/mmc_controller/hdl/rd_adv.v \
    ./modules/mmc_controller/hdl/wb_attach.v \
    ./modules/mmc_controller/hdl/crc16.v \
    ./modules/mmc_controller/hdl/crc7_d1.v \
    ./modules/mmc_controller/hdl/clk_ctrl.v \
    ./modules/system_block/hdl/system_block.v \
    ./modules/epb_wb_bridge/hdl/epb_wb_bridge.v

NETLIST_DIRS=

# Module name of toplevel entity
TOPLEVEL_MODULE=toplevel
# Logic Device Part Number
PARTNUM=xc2c256-7-VQ100

# Verilog Include Directory
VINC=include

GEN_DIR=gen
